### ISSUE TITLE
Adding a new Voice

### ISSUE THREAD

**Issue by monali-2210** [AI4Bharat/Indic-TTS#26]
How can I add another voice of my own, rather than using the one that is already provided? Do I need to change the `Speakers.pth` files?

**Comment by VivekGangurde94** [comment]
you have to fine tune the model

**Comment by AXEUS5346** [comment]
i am having trouble finding the speaker names
PS P:\Agents\Voice> & C:/Users/AXEUS/anaconda3/envs/tts/python.exe p:/Agents/Voice/indic-coqui.py
Traceback (most recent call last):
  File "p:\Agents\Voice\indic-coqui.py", line 11, in <module>
    tts.tts_to_file(text=text, file_path="output.wav")
  File "C:\Users\AXEUS\anaconda3\envs\tts\Lib\site-packages\TTS\api.py", line 372, in tts_to_file
    self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
  File "C:\Users\AXEUS\anaconda3\envs\tts\Lib\site-packages\TTS\api.py", line 280, in _check_arguments
    raise ValueError("Model is multi-speaker but no `speaker` is provided.")
ValueError: Model is multi-speaker but no `speaker` is provided.

How do i find the speaker_id?
