### ISSUE TITLE
Installation guide and ResolutionImpossible issues

### ISSUE THREAD

**Issue by SushilWagh2022** [AI4Bharat/Indic-TTS#8]
Current libraries specified in requirement files give ResolutionImpossible errors. Please provide all version of libraries to import and python on which this project will work. Also please provide an installation guide in case there are any key steps

**Comment by sandeep2244** [comment]
Getting same issue on my side, is it resolved ?

**Comment by GokulNC** [comment]
Can you please try now? There was some issue with the requirements-ml.txt which we have fixed now.

**Comment by ru2saig** [comment]
Hello!

I faced the same issue, with python 3.10.13 (via pyenv), and changed requirements-ml.txt to the following:
```
# constraints for fairseq, works with TTS as well
numba
numpy==1.22.0
protobuf==3.20

TTS==0.17.4
# onnxruntime
# TTS @ git+https://github.com/ashwin-014/TTS@deployment

ai4bharat-transliteration
asteroid
```

I was then able to successfully install all the other packages. Here's the output of pip freeze for your reference: 
```
absl-py==2.0.0
accelerate==0.23.0
ai4bharat-transliteration==1.1.3
aiohttp==3.8.5
aiosignal==1.3.1
aksharamukha==1.9.7
alabaster==0.7.13
annotated-types==0.5.0
antlr4-python3-runtime==4.8
anyascii==0.3.2
appdirs==1.4.4
asteroid==0.6.1
asteroid-filterbanks==0.4.0
async-timeout==4.0.3
attrs==23.1.0
audioread==3.0.0
Babel==2.12.1
bangla==0.0.2
bitarray==2.8.1
blinker==1.6.2
bnnumerizer==0.0.2
bnunicodenormalizer==0.1.1
boltons==23.0.0
cached-property==1.5.2
cachetools==5.3.1
cdifflib==1.2.6
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
clean-fid==0.1.35
click==8.1.7
clip-anytorch==2.5.2
colorama==0.4.6
contourpy==1.1.1
coqpit==0.0.17
cryptography==41.0.4
cycler==0.11.0
Cython==0.29.30
dateparser==1.1.8
decorator==5.1.1
Deprecated==1.2.14
dill==0.3.7
docker-pycreds==0.4.0
docopt==0.6.2
docutils==0.18.1
editdistance==0.6.2
einops==0.6.1
encodec==0.1.1
fairseq==0.12.2
ffmpeg-python==0.2.0
filelock==3.12.4
Flask==2.3.3
Flask-Cors==4.0.0
fonttools==4.42.1
frozenlist==1.4.0
fsspec==2023.9.1
ftfy==6.1.1
future==0.18.3
g2pkk==0.1.2
gevent==23.9.1
gitdb==4.0.10
GitPython==3.1.36
google-auth==2.23.0
google-auth-oauthlib==1.0.0
greenlet==2.0.2
grpcio==1.58.0
gruut==2.2.3
gruut-ipa==0.13.0
gruut-lang-de==2.0.0
gruut-lang-en==2.0.0
gruut-lang-es==2.0.0
gruut-lang-fr==2.0.2
huggingface-hub==0.17.2
hydra-core==1.0.7
idna==3.4
imageio==2.31.3
imagesize==1.4.1
indic-nlp-library==0.92
indic-numtowords==1.0.2
inflect==5.6.0
itsdangerous==2.1.2
jaconv==0.3.4
jamo==0.4.1
jieba==0.42.1
Jinja2==3.1.2
joblib==1.3.2
jsonlines==1.2.0
jsonmerge==1.9.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
julius==0.2.7
k-diffusion==0.0.16
kiwisolver==1.4.5
kornia==0.7.0
langcodes==3.3.0
language-data==1.1
lazy_loader==0.3
librosa==0.10.0
llvmlite==0.40.1
lxml==4.9.3
marisa-trie==0.7.8
Markdown==3.4.4
MarkupSafe==2.1.3
matplotlib==3.8.0
mir-eval==0.7
mock==5.1.0
Morfessor==2.0.6
msgpack==1.0.6
multidict==6.0.4
multiprocess==0.70.15
nemo-text-processing==0.2.0rc0
networkx==2.8.8
nltk==3.8.1
num2words==0.5.12
numba==0.57.0
numpy==1.22.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
omegaconf==2.0.6
packaging==23.1
pandas==2.0.3
pathos==0.3.1
pathtools==0.1.2
pb-bss-eval==0.0.2
pesq==0.0.4
Pillow==10.0.1
platformdirs==3.10.0
pooch==1.7.0
portalocker==2.8.2
pox==0.3.3
ppft==1.7.6.7
progressbar2==4.2.0
protobuf==3.20.0
psutil==5.9.5
pyarrow==13.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.3.0
pydantic_core==2.6.3
pyDeprecate==0.3.2
pydload==1.0.9
pyenchant==3.2.2
PyExecJS==1.5.1
Pygments==2.16.1
pykakasi==2.2.1
pynini==2.1.5
pynndescent==0.5.10
pyparsing==3.1.1
pypinyin==0.49.0
pysbd==0.3.4
pystoi==0.3.3
python-crfsuite==0.9.9
python-dateutil==2.8.2
python-utils==3.7.0
pytorch-lightning==1.7.7
pytorch-ranger==0.1.1
pytz==2023.3.post1
PyWavelets==1.4.1
PyYAML==6.0.1
referencing==0.30.2
regex==2023.8.8
requests==2.31.0
requests-oauthlib==1.3.1
resize-right==0.0.2
rpds-py==0.10.3
rsa==4.9
sacrebleu==2.3.1
sacremoses==0.0.53
safetensors==0.3.3
scikit-image==0.21.0
scikit-learn==1.3.1
scipy==1.11.2
sentry-sdk==1.31.0
setproctitle==1.3.2
six==1.16.0
smmap==5.0.1
snowballstemmer==2.2.0
soundfile==0.12.1
soxr==0.3.6
Sphinx==7.2.6
sphinx-argparse==0.4.0
sphinx-rtd-theme==1.3.0
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
tabulate==0.9.0
tensorboard==2.14.0
tensorboard-data-server==0.7.1
tensorboardX==2.6.2.2
threadpoolctl==3.2.0
tifffile==2023.9.18
tokenizers==0.13.3
torch==1.13.1
torch-optimizer==0.1.0
torch-stoi==0.1.2
torchaudio==0.13.1
torchdiffeq==0.2.3
torchmetrics==0.11.4
torchsde==0.2.5
torchvision==0.14.1
tqdm==4.66.1
trainer==0.0.31
trampoline==0.1.2
transformers==4.33.2
translators==5.8.5
TTS==0.17.4
typing_extensions==4.8.0
tzdata==2023.3
tzlocal==5.0.1
ujson==5.8.0
umap-learn==0.5.1
Unidecode==1.3.6
urduhack==0.1.4
urllib3==1.26.16
wandb==0.15.10
wcwidth==0.2.6
Werkzeug==2.3.7
wget==3.2
wrapt==1.15.0
yarl==1.9.2
zope.event==5.0
zope.interface==6.0
```

Are there any tests or something I could run to verify that everything is working?

**Comment by Amitt1412** [comment]
Hi there,

After installing the following packages as suggested in the trailing discussion 

```
numba
numpy==1.22.0
protobuf==3.20

TTS==0.17.4

ai4bharat-transliteration
asteroid
```


Please suggest a possible resolution. Currently I'm trying to run the same on my CPU based laptop.  I have been receiving the following error. 

```
INFO: pip is looking at multiple versions of hydra-core to determine which version is compatible with other requirements. This could take a while.
Collecting fairseq (from ai4bharat-transliteration->-r .\requirements.txt (line 10))
  Using cached fairseq-0.12.1.tar.gz (9.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "C:\Users\AmitTiwari\PycharmProjects\text_to_audio\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\AmitTiwari\PycharmProjects\text_to_audio\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\AmitTiwari\PycharmProjects\text_to_audio\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\AmitTiwari\AppData\Local\Temp\pip-build-env-ljpdyu9u\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\AmitTiwari\AppData\Local\Temp\pip-build-env-ljpdyu9u\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\AmitTiwari\AppData\Local\Temp\pip-build-env-ljpdyu9u\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "<string>", line 18, in write_version_py
      FileNotFoundError: [Errno 2] No such file or directory: 'fairseq\\version.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
````
